version: "3.9"
#revert
x-common-env: &common_env
  OLLAMA_HOST: "http://ollama:11434"
  OLLAMA_EMBED_MODEL: "nomic-embed-text"
  # Variable for the new reasoning LLM
  #OLLAMA_LLM_MODEL: "phi3"
  #OLLAMA_LLM_MODEL: "tinyllama"
  OLLAMA_LLM_MODEL: "${OLLAMA_LLM_MODEL}"
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "isc2_toronto_v3"

services:
  # Main Ollama server for all models
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 20

  # Pulls the embedding model
  ollama-pull-embed:
    image: ollama/ollama:latest
    container_name: ollama-pull-embed
    command: pull nomic-embed-text
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    volumes:
      - ollama_models:/root/.ollama

  # Pulls the reasoning model
  ollama-pull-llm:
    image: ollama/ollama:latest
    container_name: ollama-pull-llm
    #command: pull phi3
    #command: pull tinyllama
    command: pull ${OLLAMA_LLM_MODEL}
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    volumes:
      - ollama_models:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334

  rag_api:
    # Image tag for the v3-development branch
    image: docker.io/weitzman535/rag-only:v3-development
    container_name: rag-only-api
    restart: unless-stopped
    depends_on:
      ollama-pull-embed:
        condition: service_completed_successfully
      ollama-pull-llm:
        condition: service_completed_successfully
    environment:
      <<: *common_env
    ports:
      # Port 8001 to avoid conflict with v2
      - "8001:8000"
    volumes:
      - ./logs:/app/logs

volumes:
  ollama_models:
  qdrant_storage:
