version: "3.9"

x-common-env: &common_env
  OLLAMA_HOST: "http://ollama:11434"
  OLLAMA_EMBED_MODEL: "nomic-embed-text"
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "docs"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 5s
      retries: 20
  
  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    command: ollama pull nomic-embed-text
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_models:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 5s
      retries: 20

  rag_api:
    image: docker.io/weitzman535/rag-only:latest
    container_name: rag-only-api
    restart: unless-stopped
    depends_on:
      ollama-pull:
        condition: service_completed_successfully
      qdrant:
        condition: service_healthy
    environment:
      <<: *common_env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 20s
      timeout: 5s
      retries: 20

volumes:
  ollama_models:
  qdrant_storage:
